language: r
cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/src
  packages: TRUE

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
